version: '2'

services:

  nginx:
    image: nginx
    ports:
      - "5602:443"
      - "5603:444"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0

    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elastic/data/:/usr/share/elasticsearch/data/
      - ./elastic/logs/:/usr/share/elasticsearch/logs/

    environment:
      - "ES_JAVA_OPTS:-Xmx256m -Xms256m"
